[tasks.build-client]
command = "cargo"
args = ["build", "--release", "--manifest-path", "client/Cargo.toml"]

[tasks.clean-client]
cwd = "client"
command = "cargo"
args = ["clean"]

[tasks.clean-common]
cwd = "common"
command = "cargo"
args = ["clean"]

[tasks.clean]
description = "Clean both client and common directories"
dependencies = ["clean-client", "clean-common"]

[tasks.default]
description = "Build client and run cargo update in both client and common"
dependencies = ["build-client", "update-client", "update-shared"]
