name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install Cargo-Make
      run: cargo add cargo-make
      
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd driver
        cargo make default --release
    - name: Run tests
      run: cargo test --verbose
